#!/bin/sh

if ! pgrep X > /dev/null; then
    echo "${0##*/}: X isn't running"
    exit 1
fi

$BAR_TOP || b=-b

workspaces() {
    for i in $(seq $WM_WORKSPACES); do
        case $(workspace c) in
            $i) w="$w + " ;;
            *)  w="$w - " ;;
        esac
    done

    printf %s "%{B$CLR0} $w %{B-}"
}

music() {
    s=$(mpc current -f %file%)
    s=${s%%.mp3*}

    if test -n "$s"; then
        case $(mpc -f '') in
            *paused*) i= ;;
            *)        i= ;;
        esac

        printf %s "%{B$CLR8}  %{A:cover:}$i%{A} $s  %{B-}"
    fi
}

clock() {
    printf %s "  %{A:calendar:}$(date +%A\ %R)%{A}  "
}

network() {
    if s=$(iwgetid -r); then
        l=$(awk 'NR==3 { print $3 }' /proc/net/wireless)

        # XXX are these representative ranges?
        case ${l%.} in
            [1-9]|[12][0-9]|3[0-4]) i= ;;
            3[5-9]|[4-6][0-9])      i= ;;
            70)                     i= ;;
            *)                      i= ;;
        esac

        printf %s "%{B$CLR8}  $i $s  %{B-}"
    fi
}

volume() {
    m=$(amixer sget Master | grep -o '\[\(on\|off\)\]')
    v=$(amixer sget Master | grep -o '[[:digit:]]\+%')
    v=${v%%%*}

    case $v in
        [1-9]|[1-4][0-9]|50)   i= ;;
        5[1-9]|[6-9][0-9]|100) i= ;;
        *)                     i= ;;
    esac

    test "${m%%]*}" = [off && i=
    printf %s "%{B$CLR0}  %{A:vol t:}$i%{A} $v | "
}

battery() {
    m=$(cat /sys/class/power_supply/BAT0/status)
    c=$(cat /sys/class/power_supply/BAT0/capacity)

    case $m in
        Discharging) i= ;;
        Charging)    i= ;;
        *)           i= ;;
    esac

    printf %s "$i $c  %{B-}"
}

while true; do
    printf '%s%s%s\n' \
        "%{l}$(workspaces)$(music)" \
        "%{c}$(clock)" \
        "%{r}$(network)$(volume)$(battery)"
    sleep .5s
done | lemonbar \
    -g x$BAR_HEIGHT -d $b \
    -f "$(substr "$BITMAP" , 2)" \
    -f "$(substr "$BITMAP" , 1)" \
    -B$BG -F$FG \
| sh
