#!/bin/sh

if ! pgrep X > /dev/null; then
    echo "${0##*/}: X isn't running"
    exit 1
fi

$BAR_TOP || b=-b
clr1=$CLR6
clr2=$CLR14

workspaces() {
    for i in $(seq $WM_GROUPS); do
        case $(group l) in
            *$i*)
                case $(group f $(pfw 2> /dev/null)) in
                    *$i*) w="$w %{F$clr1}-%{F-} " ;;
                    *)    w="$w - " ;;
                esac
                ;;
            *)
                w="$w + "
                ;;
        esac
    done

    printf %s "%{B$clr2} $w %{B-}"
}

music() {
    s=$(mpc current -f %file%)
    s=${s%%.mp3*}

    if test -n "$s"; then
        case $(mpc -f '') in
            *paused*) i='' ;;
            *)        i='' ;;
        esac

        printf %s "%{B$clr1}  %{A:cover:}$i%{A} $s  %{B-}"
    fi
}

clock() {
    printf %s "  %{A:calendar:}$(date +%R)%{A}  "
}

network() {
    if s=$(iwgetid -r); then
        l=$(awk 'NR==3 { print $3 }' /proc/net/wireless)

        # XXX are these representative ranges?
        case ${l%.} in
            [1-9]|[12][0-9]|3[0-4]) i='' ;;
            3[5-9]|[4-6][0-9])      i='' ;;
            70)                     i='' ;;
            *)                      i='' ;;
        esac

        printf %s "  %{F$clr2}$i%{F-} $s  "
    fi
}

volume() {
    m=$(amixer sget Master | grep -o '\[\(on\|off\)\]')
    v=$(amixer sget Master | grep -o '[[:digit:]]\+%')
    v=${v%%%*}

    case $v in
        [1-9]|[1-4][0-9]|50)   i='' ;;
        5[1-9]|[6-9][0-9]|100) i='' ;;
        *)                     i='' ;;
    esac

    test "${m%%]*}" = '[off' && i=''
    printf %s "%{B$clr1}  %{A:vol mute:}$i%{A} $v%%  %{B-}"
}

battery() {
    m=$(cat /sys/class/power_supply/BAT0/status)
    c=$(cat /sys/class/power_supply/BAT0/capacity)

    case $m in
        Discharging) i='' ;;
        Charging)    i='' ;;
        *)           i='' ;;
    esac

    printf %s "%{B$clr2}  $i $c%%  %{B-}"
}

while true; do
    printf '%s%s%s\n' \
        "%{l}$(workspaces)$(music)" \
        "%{c}$(clock)" \
        "%{r}$(network)$(volume)$(battery)"
    sleep .5s
done | lemonbar \
    -g x$BAR_HEIGHT -d $b \
    -f "$(substr "$BITMAP" , 2)" \
    -f "$(substr "$BITMAP" , 1)" \
    -B$BG -F$FG \
| sh
