#!/bin/sh

if ! pgrep X > /dev/null; then
	echo "${0##*/}: X isn't running"
	exit 1
fi

dir=/tmp/calendar.lock

cleanup() {
	pkill -f ^n30f.*calendar.png
	rm -rf $dir
}

if mkdir $dir 2> /dev/null; then
	trap cleanup INT TERM

	r=$(lsw -r)
	sw=$(wattr w $r)
	sh=$(($(wattr h $r) - BAR_HEIGHT))

	# offset
	of=10

	p=$dir/calendar.png
	t=$(date '+%d %B %Y'; cal | sed -n 2,7p)

	magick $HOME/usr/img/popup/bg_normal.png \
		-fill $CLR8 -gravity center \
		-font "$(substr "$BITMAP" , 1)" \
		-annotate 0 "$t" $p

	s=$(magick $p -format %wx%h info:)
	x=$((sw/2 - ${s%x*}/2))

	if test -n "$BAR_BOTTOM"; then
		popup $x $((sh - ${s#*x} - of)) $p -d $((${s%x*}/2))
	else
		popup $x $((BAR_HEIGHT + of)) $p -u $((${s%x*}/2))
	fi
else
	cleanup
fi
