#!/bin/sh

if ! pgrep X > /dev/null; then
	echo "${0##*/}: X isn't running"
	exit 1
fi

dir=/tmp/cover.lock

cleanup() {
	pkill -f ^n30f.*cover.png
	rm -rf $dir

	trap - INT TERM
	pkill cover
}

extract() {
	p=$dir/cover.png
	w=$((${s%x*} - br*2))
	h=$((${s#*x} - br*2))

	ffmpeg -loglevel 0 -i "$HOME/usr/mus/$1" -y -vf \
		scale=$w:$h:force_original_aspect_ratio=increase,crop=$w:$h $p \
	&& popup $((of + br)) $((y + br)) $p
}

{
	if mkdir $dir 2> /dev/null; then
		trap cleanup INT TERM

		sh=$(($(wattr h $(lsw -r)) - BAR_HEIGHT))

		# offset, image border size
		of=10
		br=3

		p=$HOME/usr/img/popup/bg_cover.png
		s=$(magick $p -format %wx%h info:)
		c=$(mpc current -f %file%)

		if test -n "$BAR_BOTTOM"; then
			y=$((sh - ${s#*x} - of))
			popup $of $y $p -d $((${s%x*}/2 + 3))
		else
			y=$((BAR_HEIGHT + of))
			popup $of $y $p -u $((${s%x*}/2 + 3))
		fi

		extract "$c"

		# FIXME hangs when pkill'ed, because of --wait
		while n=$(mpc current -f %file% --wait); do
			if test "$c" != "${n:-$c}"; then
				c=$n
				pkill -f '^n30f.*-t cover.png'
				extract "$c"
			fi
		done
	fi

	cleanup
} &
