#!/bin/sh

if mkdir -p $HOME/usr/img/popup/pointer; then
    exec magick \
        -size 11x6 xc:none \
        -fill $CLR15 -draw 'path "M0,5 5,0 10,5Z"' \
        $HOME/usr/img/popup/pointer/up.png &

    exec magick \
        -size 6x11 xc:none \
        -fill $CLR15 -draw 'path "M0,5 5,0 5,10Z"' \
        $HOME/usr/img/popup/pointer/left.png &

    exec magick \
        -size 6x11 xc:none \
        -fill $CLR15 -draw 'path "M0,0 0,10 5,5Z"' \
        $HOME/usr/img/popup/pointer/right.png &

    exec magick \
        -size 11x6 xc:none \
        -fill $CLR15 -draw 'path "M0,0 5,5 10,0Z"' \
        $HOME/usr/img/popup/pointer/down.png &

    exec magick \
        -size 146x146 xc:$FG \
        -bordercolor $CLR15 -border 3 \
        $HOME/usr/img/popup/bg_normal.png &

    exec magick \
        -size 171x171 xc:$FG \
        -bordercolor $CLR15 -border 3 \
        -fill $CLR8 -gravity center \
        -font "$(substr "$BITMAP" , 1)" \
        -annotate 0 'No album cover' \
        $HOME/usr/img/popup/bg_cover.png &
fi
